// Armfield product data — all model numbers and names verified against armfield.co.uk
// official series listing (https://armfield.co.uk/armfield-products-and-solutions/).
// Each product's `id` and `name` match the published catalog entry exactly.
//
// Series prefixes (per Armfield's own taxonomy):
//   BE  Biochemical Engineering
//   C   Advanced Fluid Mechanics
//   CA  Control and Acquisition Systems
//   CE  Chemical Engineering (Reactors etc.)
//   CM  Internal Combustion Engines
//   EF  Engineering Fundamentals
//   F   Fluid Mechanics (F1-xx accessories and F-xx standalone)
//   FE  Irrigation Water Management
//   FM  Fans and Compressors (incl. pumps / turbines)
//   FS  Fluid Science
//   FT  Educational Food Technology (and IFT for Industrial)
//   H   Hydraulic Instruments
//   HT  Heat Transfer / Heat Exchange
//   PCT Process Control Teaching
//   RA  Refrigeration & Air Conditioning
//   S   Applied Hydraulics & Hydrology
//   TH  Thermodynamics
//   UOP Unit Operations
//   W   Water Treatment

window.ARMFIELD_DATA = {
  majors: [
    {
      id: "mech",
      name: "Mechanical Engineering",
      blurb: "Fluids, thermal systems, engines, HVAC",
      glyph: "mech",
      categories: ["fluid-mech", "adv-fluid", "fans-comp", "heat-transfer-hx", "heat-transfer-tx", "thermo", "ic-engines", "refrig"],
    },
    {
      id: "chem",
      name: "Chemical Engineering",
      blurb: "Unit operations, reactors, biochemical processes",
      glyph: "chem",
      categories: ["unit-ops", "reactors", "biochem", "process-control", "heat-transfer-hx"],
    },
    {
      id: "civil",
      name: "Civil Engineering",
      blurb: "Hydraulics, hydrology, open channel flow",
      glyph: "civil",
      categories: ["hydraulics", "research-flume", "adv-fluid", "fluid-mech", "h-instruments"],
    },
    {
      id: "food",
      name: "Food Science & Technology",
      blurb: "Educational food tech and industrial processing",
      glyph: "food",
      categories: ["ft-edu", "ift"],
    },
    {
      id: "env",
      name: "Environmental Engineering",
      blurb: "Water, wastewater, filtration, irrigation",
      glyph: "env",
      categories: ["water-treat", "irrigation"],
    },
    {
      id: "mtx",
      name: "Mechatronics & Control",
      blurb: "Process control loops, data acquisition",
      glyph: "mtx",
      categories: ["process-control", "daq"],
    },
  ],

  categories: {
    "fluid-mech":       { name: "Fluid Mechanics",                     series: "F series",     tag: "Fluids" },
    "adv-fluid":        { name: "Advanced Fluid Mechanics",            series: "C series",     tag: "Fluids" },
    "fans-comp":        { name: "Fans, Pumps & Compressors",           series: "FM series",    tag: "Fluids" },
    "heat-transfer-tx": { name: "Heat Transfer",                       series: "HT10XC family", tag: "Thermal" },
    "heat-transfer-hx": { name: "Heat Exchangers",                     series: "HT30XC family", tag: "Thermal" },
    "thermo":           { name: "Thermodynamics",                      series: "TH series",    tag: "Thermal" },
    "ic-engines":       { name: "Internal Combustion Engines",         series: "CM series",    tag: "Thermal" },
    "refrig":           { name: "Refrigeration & Air Conditioning",    series: "RA series",    tag: "Thermal" },
    "unit-ops":         { name: "Unit Operations",                     series: "UOP series",   tag: "Process" },
    "reactors":         { name: "Chemical Reactors",                   series: "CE series",    tag: "Process" },
    "biochem":          { name: "Biochemical Engineering",             series: "BE series",    tag: "Process" },
    "process-control":  { name: "Process Control",                     series: "PCT series",   tag: "Control" },
    "hydraulics":       { name: "Applied Hydraulics & Hydrology",      series: "S series",     tag: "Civil" },
    "research-flume":   { name: "Research Flumes",                     series: "S60/S80/S100", tag: "Civil" },
    "h-instruments":    { name: "Hydraulic Instruments",               series: "H series",     tag: "Civil" },
    "ft-edu":           { name: "Educational Food Technology",         series: "FT series",    tag: "Food" },
    "ift":              { name: "Industrial Food Technology",          series: "FT / IFT",     tag: "Food" },
    "water-treat":      { name: "Water Treatment",                     series: "W series",     tag: "Environmental" },
    "irrigation":       { name: "Irrigation Water Management",         series: "FE series",    tag: "Environmental" },
    "daq":              { name: "Control & Acquisition Systems",       series: "CA series",    tag: "Control" },
  },

  products: [
    // ============== F1 Series – Fluid Mechanics ==============
    { id:"F1-10", name:"Hydraulics Bench", cat:"fluid-mech", use:"Teaching",
      desc:"Self-contained mobile bench providing controlled water supply for F1 accessory experiments.",
      experiments:["Base unit for the F1 accessory range","Volumetric and gravimetric flow measurement","Closed-loop recirculation with integral sump","Accepts F1-11 through F1-38 modules"],
      related:["F1-15-MKII","F1-18","F1-22-MKII"] },
    { id:"F1-11", name:"Dead Weight Pressure Gauge Calibrator", cat:"fluid-mech", use:"Teaching",
      desc:"Primary-standard dead-weight tester for calibration of Bourdon-type pressure gauges.",
      experiments:["Calibration of a Bourdon gauge","Pressure-force-area relationship","Gauge hysteresis and repeatability"],
      related:["F1-11","F1-29"] },
    { id:"F1-12-MKII", name:"Hydrostatic Pressure", cat:"fluid-mech", use:"Teaching",
      desc:"Quadrant tank for measuring hydrostatic thrust on a partially and fully submerged surface.",
      experiments:["Centre of pressure determination","Moments of hydrostatic force","Partially vs fully submerged cases"],
      related:["F1-29","F1-31"] },
    { id:"F1-13-MKII", name:"Flow Over Weir", cat:"fluid-mech", use:"Teaching",
      desc:"Interchangeable rectangular and V-notch weirs for head–discharge characterisation.",
      experiments:["Cd for a rectangular weir","Cd for a V-notch weir","Head-discharge relationship"],
      related:["F1-10","F1-19"] },
    { id:"F1-14-MKII", name:"Metacentric Height", cat:"fluid-mech", use:"Teaching",
      desc:"Pontoon with adjustable weight for measuring metacentric height and stability of floating bodies.",
      experiments:["Metacentric height from list angle","Centre of gravity effects","Stability margin of floating bodies"],
      related:["F1-29"] },
    { id:"F1-15-MKII", name:"Bernoulli's Theorem Demonstration", cat:"fluid-mech", use:"Teaching",
      desc:"Venturi-shaped test section with piezometer tappings to verify the Bernoulli equation.",
      experiments:["Static vs total head comparison","Venturi discharge coefficient","Energy conservation along a streamline"],
      related:["F1-10","F1-21-MKII"] },
    { id:"F1-16-MKII", name:"Impact of a Jet", cat:"fluid-mech", use:"Teaching",
      desc:"Measures force produced by a water jet striking flat, hemispherical and conical vanes.",
      experiments:["Momentum equation verification","Force vs vane geometry","Flow rate vs impact force"],
      related:["F1-10"] },
    { id:"F1-17", name:"Orifice and Free Jet Flow", cat:"fluid-mech", use:"Teaching",
      desc:"Investigates jet trajectory and discharge coefficients from sharp-edged orifices.",
      experiments:["Cd under varying heads","Jet trajectory plotting","Coefficients Cv and Cc"],
      related:["F1-10","F1-17a"] },
    { id:"F1-17a", name:"Orifice Discharge", cat:"fluid-mech", use:"Teaching",
      desc:"Simplified orifice discharge apparatus for comparing small- and large-aperture orifices.",
      experiments:["Discharge coefficient determination","Aperture size effects","Head-discharge relationship"],
      related:["F1-17"] },
    { id:"F1-18", name:"Energy Losses in Pipes", cat:"fluid-mech", use:"Teaching",
      desc:"Parallel pipe test section for measuring friction losses in laminar and turbulent flow.",
      experiments:["Darcy friction factor","Reynolds number transition","Pipe roughness effects"],
      related:["F1-10","C6-MKII-10"] },
    { id:"F1-19", name:"Flow Channel", cat:"fluid-mech", use:"Teaching",
      desc:"Small open channel with interchangeable weirs and gates for introductory open-channel flow studies.",
      experiments:["Flow under a sluice gate","Flow over a broad-crested weir","Specific energy diagrams"],
      related:["F1-10","F1-13-MKII"] },
    { id:"F1-20", name:"Osborne Reynolds Demonstration", cat:"fluid-mech", use:"Teaching",
      desc:"Classical dye-injection apparatus for visualising laminar, transitional and turbulent flow.",
      experiments:["Reynolds number determination","Transition point observation","Dye-trace flow visualisation"],
      related:["F1-20"] },
    { id:"F1-21-MKII", name:"Flow Meter Demonstration", cat:"fluid-mech", use:"Teaching",
      desc:"Series-connected Venturi, orifice and rotameter flow meters for comparative study.",
      experiments:["Calibration of three flow meters","Head loss across each meter","Meter accuracy vs flow"],
      related:["F1-10","C9-MKII"] },
    { id:"F1-22-MKII", name:"Energy Losses in Bends and Fittings", cat:"fluid-mech", use:"Teaching",
      desc:"Circuit of bends, sudden expansions, contractions and valves for minor loss studies.",
      experiments:["Loss coefficients K for bends","Sudden enlargement / contraction losses","Valve characteristic"],
      related:["F1-10","F1-18"] },
    { id:"F1-23", name:"Free and Forced Vortex", cat:"fluid-mech", use:"Teaching",
      desc:"Cylindrical vessel for producing and profiling free and forced vortex flows.",
      experiments:["Free vortex surface profile","Forced vortex parabolic profile","Angular velocity measurement"],
      related:["F1-10"] },
    { id:"F1-24", name:"Hydraulic Ram", cat:"fluid-mech", use:"Teaching",
      desc:"Working model of a hydraulic ram pump for studying water-hammer-driven lift.",
      experiments:["Ram efficiency vs delivery head","Waste-water vs lift ratio","Cycle frequency effects"],
      related:["F1-10"] },
    { id:"F1-25-MKII", name:"Demonstration Pelton Turbine", cat:"fluid-mech", use:"Teaching",
      desc:"Small-scale Pelton wheel for studying impulse turbine performance.",
      experiments:["Torque–speed curves","Turbine efficiency vs flow","Nozzle characteristics"],
      related:["FM62-Pelton-Turbines","F1-10"] },
    { id:"F1-27", name:"Centrifugal Pump Characteristics", cat:"fluid-mech", use:"Teaching",
      desc:"Single-stage centrifugal pump test set with head, flow and power instrumentation.",
      experiments:["Head–flow characteristic","Efficiency curves","Affinity laws at different speeds"],
      related:["F1-35","FM51"] },
    { id:"F1-28", name:"Cavitation Demonstration", cat:"fluid-mech", use:"Teaching",
      desc:"Transparent Venturi section allowing direct observation of cavitation onset.",
      experiments:["Cavitation onset at throat","Pressure vs flow conditions","NPSH concepts"],
      related:["F1-27"] },
    { id:"F1-29", name:"Fluid Statics and Manometry", cat:"fluid-mech", use:"Teaching",
      desc:"Introductory bench covering hydrostatic pressure, manometry and buoyancy.",
      experiments:["U-tube and inclined manometry","Archimedes' principle","Hydrostatic head comparisons"],
      related:["F1-12-MKII","F1-31"] },
    { id:"F1-30", name:"Fluid Properties Apparatus", cat:"fluid-mech", use:"Teaching",
      desc:"Multi-station rig for measuring density, viscosity, surface tension and capillarity.",
      experiments:["Falling sphere viscometry","Surface tension by capillary rise","Relative density"],
      related:["F1-29"] },
    { id:"F1-31", name:"Pascal's Apparatus", cat:"fluid-mech", use:"Teaching",
      desc:"Classical Pascal apparatus demonstrating pressure transmission through a fluid.",
      experiments:["Pascal's law verification","Pressure independence of container shape"],
      related:["F1-29"] },
    { id:"F1-32", name:"Francis Turbine", cat:"fluid-mech", use:"Teaching",
      desc:"Bench-top Francis reaction turbine for performance characterisation.",
      experiments:["Power vs flow","Speed-torque relationship","Reaction turbine efficiency"],
      related:["FM61","F1-25-MKII"] },
    { id:"F1-33", name:"Pitot Tube Demonstrator", cat:"fluid-mech", use:"Teaching",
      desc:"Traversing Pitot-static tube in a duct for velocity profile measurement.",
      experiments:["Velocity profile across a pipe","Mean vs maximum velocity","Stagnation pressure concepts"],
      related:["H30"] },
    { id:"F1-35", name:"Series and Parallel Pumps", cat:"fluid-mech", use:"Teaching",
      desc:"Pair of matched centrifugal pumps switchable between series and parallel configurations.",
      experiments:["Series vs single pump head","Parallel vs single pump flow","System curve intersection"],
      related:["F1-27","FM51"] },
    { id:"F1-38", name:"Hele Shaw Apparatus", cat:"fluid-mech", use:"Research",
      desc:"Parallel-plate Hele-Shaw cell for two-dimensional ideal flow visualisation.",
      experiments:["Flow past immersed bodies","Source / sink superposition","Laplacian flow analogy"],
      related:["C10"] },

    // ============== C Series – Advanced Fluid Mechanics ==============
    { id:"C1-MKII", name:"Compressible Flow Unit", cat:"adv-fluid", use:"Research",
      desc:"Converging-diverging nozzle rig for studying choked and supersonic flow.",
      experiments:["Nozzle pressure distribution","Choked flow conditions","Shock wave observation"],
      related:["C2","C15"] },
    { id:"C2", name:"Subsonic Wind Tunnel", cat:"adv-fluid", use:"Teaching",
      desc:"Open-circuit subsonic wind tunnel for aerodynamic force measurement.",
      experiments:["Lift and drag on aerofoils","Pressure distribution","Boundary layer studies"],
      related:["C15","C30"] },
    { id:"C3-MKII", name:"Multi-Pump Test Rig", cat:"adv-fluid", use:"Research",
      desc:"Three-pump configurable rig for series, parallel and combined pump studies.",
      experiments:["Series / parallel switching","Matching pumps to a system curve","Combined characteristic curves"],
      related:["FM51","F1-35"] },
    { id:"C4-MKII", name:"Multi-Purpose Teaching Flume", cat:"adv-fluid", use:"Teaching",
      desc:"Tilting glass-sided flume with interchangeable weirs, gates and models.",
      experiments:["Hydraulic jump characterisation","Flow over weirs and spillways","Sluice gate discharge"],
      related:["S16","S28"] },
    { id:"C6-MKII-10", name:"Fluid Friction Measurements", cat:"adv-fluid", use:"Teaching",
      desc:"Pipe-network rig for measuring friction in pipes, bends, valves and flow meters.",
      experiments:["Friction factor vs Re","Loss coefficients for fittings","Flow meter calibration"],
      related:["F1-18","F1-22-MKII"] },
    { id:"C7-MKII", name:"Pipe Surge and Water Hammer Apparatus", cat:"adv-fluid", use:"Research",
      desc:"Quick-closing-valve rig for studying transient pressure waves in pipelines.",
      experiments:["Water hammer pressure rise","Surge tank response","Wave speed measurement"],
      related:["C6-MKII-10"] },
    { id:"C9", name:"Flow Meter Demonstration Unit", cat:"adv-fluid", use:"Teaching",
      desc:"Standalone rig comparing Venturi, orifice plate and rotameter meters.",
      experiments:["Comparative meter calibration","Head loss across each meter","Discharge coefficients"],
      related:["F1-21-MKII"] },
    { id:"C9-MKII", name:"Flowmeter Demonstrator", cat:"adv-fluid", use:"Teaching",
      desc:"Updated flowmeter rig with enhanced instrumentation and data logging.",
      experiments:["Calibration of multiple meter types","Accuracy and repeatability","Reynolds number effects"],
      related:["C9"] },
    { id:"C10", name:"Laminar Flow Table", cat:"adv-fluid", use:"Teaching",
      desc:"Dyed flow table for visualising two-dimensional laminar patterns and streamlines.",
      experiments:["Streamline visualisation","Flow around immersed objects","Source / sink superposition"],
      related:["F1-38"] },
    { id:"C11-MKII", name:"Pipe Networks", cat:"adv-fluid", use:"Research",
      desc:"Configurable pipe network for teaching Hardy-Cross and network analysis methods.",
      experiments:["Hardy-Cross iteration","Flow distribution in networks","Head loss balancing"],
      related:["C6-MKII-10"] },
    { id:"C15", name:"Computer Controlled Subsonic Wind Tunnel", cat:"adv-fluid", use:"Research",
      desc:"Fully instrumented subsonic wind tunnel with PC-based control and force balance.",
      experiments:["Lift, drag and pitching moment","Computerised data logging","Angle of attack sweeps"],
      related:["C2","C30"] },
    { id:"C16", name:"Hydrogen Bubble Flow Visualisation System", cat:"adv-fluid", use:"Research",
      desc:"Wire-generated hydrogen bubbles for time-line flow visualisation in a water channel.",
      experiments:["Time-line visualisation","Velocity profile imaging","Boundary layer observation"],
      related:["C10"] },
    { id:"C30", name:"Subsonic Wind Tunnel", cat:"adv-fluid", use:"Research",
      desc:"Large-section computer-controlled subsonic wind tunnel for advanced aerodynamic testing.",
      experiments:["High Re aerofoil testing","Wake surveys","3-component force measurement"],
      related:["C15","C2"] },

    // ============== FM Series – Fans, Pumps & Turbines ==============
    { id:"FM40", name:"Centrifugal Fan Demonstration Unit", cat:"fans-comp", use:"Teaching",
      desc:"Bench-top centrifugal fan with variable speed and throttle for performance characterisation.",
      experiments:["Pressure–volume flow characteristic","Fan efficiency","Speed scaling laws"],
      related:["FM51"] },
    { id:"FM51", name:"Series and Parallel Pumps Demonstration", cat:"fans-comp", use:"Teaching",
      desc:"Dual centrifugal pump unit switchable between series and parallel operation.",
      experiments:["Series vs single pump head","Parallel vs single pump flow","System operating point"],
      related:["F1-35","C3-MKII"] },
    { id:"FM52", name:"Gear Pump Demonstration Unit", cat:"fans-comp", use:"Teaching",
      desc:"External-gear positive-displacement pump rig for viscous-fluid performance studies.",
      experiments:["Flow vs back pressure","Volumetric efficiency","Slip characterisation"],
      related:["FM53"] },
    { id:"FM53", name:"Plunger Pump Demonstration Unit", cat:"fans-comp", use:"Teaching",
      desc:"Reciprocating plunger pump rig illustrating positive displacement principles.",
      experiments:["Discharge pulsation","Volumetric efficiency","Effect of air vessel"],
      related:["FM52"] },
    { id:"FM60", name:"Impulse Turbine", cat:"fans-comp", use:"Teaching",
      desc:"Bench-top impulse turbine for torque–speed characterisation.",
      experiments:["Torque vs speed","Power output curves","Efficiency characterisation"],
      related:["FM61","FM62-Pelton-Turbines"] },
    { id:"FM61", name:"Reaction Turbine", cat:"fans-comp", use:"Teaching",
      desc:"Small-scale reaction turbine rig for hydraulic performance studies.",
      experiments:["Reaction turbine torque–speed","Power vs flow","Efficiency vs guide vane angle"],
      related:["F1-32"] },
    { id:"FM62-Pelton-Turbines", name:"Pelton Turbines", cat:"fans-comp", use:"Teaching",
      desc:"Pelton impulse turbine unit with nozzle and spear-valve adjustment.",
      experiments:["Pelton wheel performance","Nozzle and spear valve effects","Jet-deflector braking"],
      related:["F1-25-MKII","FM60"] },
    { id:"FM63", name:"Propeller Turbine", cat:"fans-comp", use:"Teaching",
      desc:"Axial-flow propeller turbine for low-head high-flow applications.",
      experiments:["Performance at low head","Blade pitch effects","Propeller efficiency"],
      related:["FM61"] },
    { id:"FM64", name:"Pump Test Accessory", cat:"fans-comp", use:"Teaching",
      desc:"Instrumented accessory for adding standard performance testing to a pump bench.",
      experiments:["Pump curve generation","NPSH estimation","Efficiency measurement"],
      related:["F1-27","FM51"] },

    // ============== HT Series – Heat Transfer (HT10XC family) ==============
    { id:"HT10XC", name:"Computer Controlled Heat Transfer Teaching Equipment", cat:"heat-transfer-tx", use:"Research",
      desc:"Base service unit providing instrumentation and PC control for the HT10XC accessory range.",
      experiments:["Host for HT11 – HT20 accessories","Multi-channel thermocouple logging","PC-based control"],
      related:["HT11","HT12","HT14","HT15"] },
    { id:"HT11", name:"Linear Heat Conduction", cat:"heat-transfer-tx", use:"Teaching",
      desc:"Composite bar specimens for measuring 1-D conduction and thermal conductivity.",
      experiments:["Fourier's law verification","Thermal conductivity k","Contact resistance"],
      related:["HT10XC","HT12"] },
    { id:"HT12", name:"Radial Heat Conduction", cat:"heat-transfer-tx", use:"Teaching",
      desc:"Brass disc with radial heat flow to study steady-state 2-D conduction.",
      experiments:["Radial temperature profile","Log-law conduction","Conductivity of brass"],
      related:["HT10XC","HT11"] },
    { id:"HT13", name:"Laws of Radiant Heat Transfer and Radiant Heat Exchange", cat:"heat-transfer-tx", use:"Research",
      desc:"Radiometer apparatus for studying radiation laws and surface properties.",
      experiments:["Stefan-Boltzmann constant","Inverse-square relationship","Kirchhoff's law"],
      related:["HT10XC","HT16"] },
    { id:"HT14", name:"Combined Convection and Radiation", cat:"heat-transfer-tx", use:"Teaching",
      desc:"Heated cylinder studying the relative contributions of convection and radiation.",
      experiments:["Natural and forced convection coefficients","Radiation share of total flux","Surface finish effects"],
      related:["HT10XC","HT19C"] },
    { id:"HT15", name:"Extended Surface Heat Exchanger", cat:"heat-transfer-tx", use:"Teaching",
      desc:"Heated pin-fin specimen for combined conduction-convection studies.",
      experiments:["Fin temperature distribution","Fin efficiency","Heat transfer coefficient h"],
      related:["HT10XC"] },
    { id:"HT16", name:"Radiation Errors in Temperature Measurement", cat:"heat-transfer-tx", use:"Research",
      desc:"Rig for evaluating radiation errors in thermocouple measurement of gas temperature.",
      experiments:["Radiation error quantification","Shield geometry effects","Correction methodologies"],
      related:["HT10XC","HT13"] },
    { id:"HT17", name:"Unsteady-State Heat Transfer", cat:"heat-transfer-tx", use:"Research",
      desc:"Instrumented metal shapes for transient-conduction and Biot/Fourier number studies.",
      experiments:["Transient cooling curves","Biot number significance","Lumped vs distributed analysis"],
      related:["HT10XC"] },
    { id:"HT18C", name:"Thermo-Electric Heat Pump", cat:"heat-transfer-tx", use:"Research",
      desc:"Peltier-effect heat pump for reversible heating and cooling performance studies.",
      experiments:["COP as heat pump vs refrigerator","Current vs heat-flow","Peltier effect quantification"],
      related:["HT10XC"] },
    { id:"HT19C", name:"Free and Forced Convection", cat:"heat-transfer-tx", use:"Teaching",
      desc:"Vertical heated tube with interchangeable specimens for convection coefficient studies.",
      experiments:["Free-convection coefficient","Forced-convection coefficient","Fin enhancement comparison"],
      related:["HT10XC","HT14"] },
    { id:"HT20", name:"Conductivity of Liquids and Gases", cat:"heat-transfer-tx", use:"Research",
      desc:"Thin-film cell for measuring thermal conductivity of fluids with minimal convection.",
      experiments:["Thermal conductivity of water","Conductivity of air / gases","Temperature dependence"],
      related:["HT10XC"] },

    // ============== HT Series – Heat Exchangers (HT30XC family) ==============
    { id:"HT30XC", name:"Computer Controlled Heat Exchanger Service Module", cat:"heat-transfer-hx", use:"Research",
      desc:"Service unit providing flows, temperatures and DAQ for interchangeable HT3x exchangers.",
      experiments:["Host for HT31 – HT37","Parallel vs counter flow","LMTD and effectiveness-NTU"],
      related:["HT31","HT32","HT33","HT34"] },
    { id:"HT31", name:"Tubular Heat Exchanger", cat:"heat-transfer-hx", use:"Teaching",
      desc:"Concentric-tube heat exchanger for basic parallel- and counter-flow studies.",
      experiments:["Parallel vs counter flow","Overall U determination","LMTD method"],
      related:["HT30XC","HT32","HT33"] },
    { id:"HT32", name:"Plate Heat Exchanger", cat:"heat-transfer-hx", use:"Teaching",
      desc:"Gasketed plate heat exchanger module with configurable plate count.",
      experiments:["Plate count vs effectiveness","NTU analysis","Pressure drop characterisation"],
      related:["HT30XC","HT31"] },
    { id:"HT33", name:"Shell and Tube Heat Exchanger", cat:"heat-transfer-hx", use:"Research",
      desc:"Multi-pass shell-and-tube module for realistic industrial-style exchanger studies.",
      experiments:["Shell-side vs tube-side analysis","Baffle effect on U","Multi-pass correction factors"],
      related:["HT30XC","HT31"] },
    { id:"HT34", name:"Jacketed Vessel With Coil & Stirrer", cat:"heat-transfer-hx", use:"Research",
      desc:"Stirred, jacketed vessel with helical coil for batch heating/cooling studies.",
      experiments:["Jacket vs coil heat transfer","Effect of stirrer speed","Batch heating curves"],
      related:["HT30XC"] },
    { id:"HT35", name:"Cross Flow Heat Exchanger", cat:"heat-transfer-hx", use:"Research",
      desc:"Air–water cross-flow exchanger for studying tube-bank heat transfer.",
      experiments:["Cross-flow correction factors","Air-side vs water-side U","Tube-bundle arrangement effects"],
      related:["HT30XC"] },
    { id:"HT36", name:"Extended Tubular Heat Exchanger", cat:"heat-transfer-hx", use:"Research",
      desc:"Extended-length tubular exchanger providing a wider range of temperature profiles.",
      experiments:["Axial temperature profile","Length vs effectiveness","Combined mode analysis"],
      related:["HT30XC","HT31"] },
    { id:"HT37", name:"Extended Reconfigurable Heat Exchanger", cat:"heat-transfer-hx", use:"Research",
      desc:"Reconfigurable multi-mode exchanger for advanced research studies.",
      experiments:["Multi-configuration comparison","Flow arrangement effects","Advanced modelling benchmarks"],
      related:["HT30XC"] },

    // ============== TH Series – Thermodynamics ==============
    { id:"TH1", name:"Temperature Measurement and Calibration", cat:"thermo", use:"Teaching",
      desc:"Multi-sensor rig for comparing thermocouples, RTDs and thermistors.",
      experiments:["Calibration against a reference","Sensor time-response","Stem conduction errors"],
      related:["TH2"] },
    { id:"TH2", name:"Pressure Measurement and Calibration", cat:"thermo", use:"Teaching",
      desc:"Calibration rig covering manometers, Bourdon gauges and electronic transducers.",
      experiments:["Absolute vs gauge pressure","Calibration curves","Transducer linearity"],
      related:["F1-11","TH1"] },
    { id:"TH3", name:"Saturation Pressure", cat:"thermo", use:"Teaching",
      desc:"Boiler with pressure and temperature sensors for a saturated-steam P–T curve.",
      experiments:["P–T relationship for water","Clausius-Clapeyron verification","Steam table comparison"],
      related:["TH5"] },
    { id:"TH4", name:"Recycle Loops", cat:"thermo", use:"Teaching",
      desc:"Thermo-fluid loop demonstrating recycle and energy-balance principles.",
      experiments:["Mass and energy balances","Recycle ratio effects","Steady-state operation"],
      related:["TH3"] },
    { id:"TH5", name:"Expansion Process of a Perfect Gas", cat:"thermo", use:"Teaching",
      desc:"Two-vessel gas apparatus for studying isothermal and adiabatic expansion.",
      experiments:["Adiabatic exponent γ","Isothermal vs adiabatic expansion","PV relationships"],
      related:["TH3","TH4"] },
    { id:"TH6", name:"Film and Dropwise Condensation Demonstration Unit", cat:"thermo", use:"Research",
      desc:"Condensation rig for comparing film and dropwise regimes on treated surfaces.",
      experiments:["Film vs dropwise h","Effect of surface treatment","Condensate flux measurement"],
      related:["HT30XC"] },

    // ============== RA Series – Refrigeration & Air Conditioning ==============
    { id:"RA1-MKII", name:"Computer Controlled Vapour-Compression Refrigeration Unit", cat:"refrig", use:"Research",
      desc:"Full vapour-compression refrigeration cycle with computer-based instrumentation and control.",
      experiments:["P–h diagram construction","COP determination","Superheat and subcooling","Load variation effects"],
      related:["RA2","RA3"] },
    { id:"RA2", name:"Computer Controlled Air Conditioning Unit", cat:"refrig", use:"Research",
      desc:"Full psychrometric duct with heating, cooling, humidification and re-heat stations.",
      experiments:["Psychrometric process plotting","Sensible and latent loads","Cooling coil bypass factor"],
      related:["RA1-MKII","RA3"] },
    { id:"RA3", name:"Recirculating Air Conditioning Unit", cat:"refrig", use:"Teaching",
      desc:"Recirculating air-conditioning rig for variable mix-ratio studies.",
      experiments:["Fresh-air vs recirculation mixing","Space load simulation","Comfort-zone envelope"],
      related:["RA2"] },
    { id:"RA4", name:"Air-Conditioning Training Unit", cat:"refrig", use:"Teaching",
      desc:"Industrial-style A/C training rig with split unit and service instrumentation.",
      experiments:["Split-system commissioning","Fault-finding exercises","Refrigerant charge effects"],
      related:["RA2","RA3"] },

    // ============== UOP Series – Unit Operations ==============
    { id:"UOP3", name:"Distillation Columns", cat:"unit-ops", use:"Research",
      desc:"Continuous and batch distillation column platform for binary separation studies.",
      experiments:["McCabe-Thiele analysis","Reflux ratio effects","Column efficiency (HETP)","Binary separation trials"],
      related:["UOP5-MKII","UOP7-MKII"] },
    { id:"UOP4-MKII", name:"Solid/Liquid Extraction Unit", cat:"unit-ops", use:"Research",
      desc:"Continuous counter-current solid-liquid extraction column.",
      experiments:["Stage efficiency","Solvent-to-feed ratio","Mass transfer coefficients"],
      related:["UOP3","UOP5-MKII"] },
    { id:"UOP5-MKII", name:"Liquid/Liquid Extraction Unit", cat:"unit-ops", use:"Research",
      desc:"Packed column for immiscible liquid-liquid mass transfer studies.",
      experiments:["Extraction efficiency","Distribution coefficients","Flooding velocity"],
      related:["UOP7-MKII","UOP4-MKII"] },
    { id:"UOP6-MKII", name:"Computer Controlled Water Cooling Tower", cat:"unit-ops", use:"Research",
      desc:"Counter-current packed cooling tower with PC-based data acquisition.",
      experiments:["Cooling range and approach","Mass and energy balances","Effect of packing type"],
      related:["UOP3"] },
    { id:"UOP7-MKII", name:"Gas Absorption Column", cat:"unit-ops", use:"Research",
      desc:"Packed column for studying gas-liquid mass transfer and pressure drop.",
      experiments:["Flooding and loading limits","Absorption of CO₂ into NaOH","KGa determination","Pressure drop vs flow"],
      related:["UOP3","UOP5-MKII"] },
    { id:"UOP8-MkIIe", name:"Computer Controlled Tray Dryer", cat:"unit-ops", use:"Research",
      desc:"Tray dryer with PC-controlled temperature, air velocity and humidity.",
      experiments:["Drying curve characterisation","Constant and falling rate periods","Effect of air velocity"],
      related:["UOP20X"] },
    { id:"UOP10", name:"Laboratory Steam Generator", cat:"unit-ops", use:"Research",
      desc:"Compact steam generator providing laboratory-scale steam for unit operations experiments.",
      experiments:["Steam generation capacity","Superheat vs wet steam","Auxiliary for UOP rigs"],
      related:["UOP3","UOP20X"] },
    { id:"UOP12", name:"Filtration Unit", cat:"unit-ops", use:"Teaching",
      desc:"Plate-and-frame filter press for studying cake filtration.",
      experiments:["Cake filtration equation","Specific cake resistance","Compressibility effects"],
      related:["W5-MKII"] },
    { id:"UOP14-MKII", name:"Crystallisation Unit", cat:"unit-ops", use:"Research",
      desc:"Stirred vessel with controlled cooling for batch crystallisation studies.",
      experiments:["Cooling curves and nucleation","Crystal size distribution","Seeding effects"],
      related:["UOP3"] },
    { id:"UOP15", name:"Fixed Bed Adsorption Unit", cat:"unit-ops", use:"Research",
      desc:"Packed adsorption column for studying breakthrough curves and adsorbent capacity.",
      experiments:["Breakthrough curve analysis","Adsorbent capacity","Mass transfer zone length"],
      related:["UOP7-MKII"] },
    { id:"UOP20X", name:"Computer Controlled Modular Evaporator Series", cat:"unit-ops", use:"Research",
      desc:"Modular rising- or falling-film evaporator supporting single / double effect and multiple feed configurations.",
      experiments:["Overall U determination","Single vs double effect","Forward / backward / parallel feed","Boiling point elevation"],
      related:["UOP8-MkIIe","UOP3"] },
    { id:"UOP30", name:"3-Phase Horizontal Separator", cat:"unit-ops", use:"Research",
      desc:"Oil-water-gas horizontal separator for studying phase separation dynamics.",
      experiments:["Oil-water interface control","Gas carry-over","Retention time effects"],
      related:["UOP20X"] },

    // ============== CE Series – Chemical Engineering (Reactors) ==============
    { id:"CEXC", name:"Chemical Reactors Teaching Equipment – Service Unit", cat:"reactors", use:"Research",
      desc:"Service unit providing pumps, heaters and PC-based DAQ for the CE reactor range.",
      experiments:["Host for CEB, CEM, CET, CEY, CEZ","Multi-channel logging","Temperature and flow control"],
      related:["CEB-MKIII","CEM-MKII","CET-MKII","CEY","CEZ"] },
    { id:"CEB-MKIII", name:"Transparent Batch Reactor", cat:"reactors", use:"Research",
      desc:"Transparent stirred-tank reactor for batch and semi-batch reaction studies.",
      experiments:["Reaction rate constant k","Arrhenius activation energy","Semi-batch addition strategies"],
      related:["CEXC","CEM-MKII"] },
    { id:"CEK-MKII", name:"Fluid Mixing Studies", cat:"reactors", use:"Teaching",
      desc:"Transparent stirred vessel with interchangeable impellers for mixing-power studies.",
      experiments:["Power number vs Reynolds","Blend time measurement","Impeller type comparison"],
      related:["CEB-MKIII"] },
    { id:"CEL-MKII", name:"Fixed and Fluidised Bed Apparatus", cat:"reactors", use:"Teaching",
      desc:"Transparent column for studying packed and fluidised bed behaviour.",
      experiments:["Minimum fluidisation velocity","Pressure drop vs flow","Bed expansion"],
      related:["CEN-MKII"] },
    { id:"CEM-MKII", name:"Continuous Stirred Tank Reactor (CSTR)", cat:"reactors", use:"Research",
      desc:"Single CSTR for residence-time-distribution and continuous reaction studies.",
      experiments:["RTD via pulse and step tests","Conversion vs residence time","CSTR vs PFR comparison"],
      related:["CEXC","CEP-MKII","CET-MKII"] },
    { id:"CEN-MKII", name:"Solids Handling Studies", cat:"reactors", use:"Teaching",
      desc:"Bench rig for characterising flow and angle-of-repose properties of granular solids.",
      experiments:["Angle of repose","Hopper discharge rates","Particle size segregation"],
      related:["CEL-MKII"] },
    { id:"CEP-MKII", name:"Stirred Tank Reactors in Series", cat:"reactors", use:"Research",
      desc:"Cascade of CSTRs in series for RTD and conversion studies.",
      experiments:["Tanks-in-series model","Cumulative RTD E(t)","N-tank conversion improvement"],
      related:["CEM-MKII","CEXC"] },
    { id:"CEQ", name:"Corrosion Studies Kit", cat:"reactors", use:"Teaching",
      desc:"Electrochemical kit for studying corrosion mechanisms and protection methods.",
      experiments:["Galvanic series","Cathodic protection","Corrosion rate measurement"],
      related:[] },
    { id:"CERa-MKII", name:"Gaseous Diffusion Coefficient Apparatus", cat:"reactors", use:"Research",
      desc:"Stefan-tube style apparatus for measuring gaseous diffusion coefficients.",
      experiments:["Stefan-tube diffusion","Diffusivity temperature dependence","Binary gas systems"],
      related:["CERb"] },
    { id:"CERb", name:"Liquid Diffusion Coefficient Apparatus", cat:"reactors", use:"Research",
      desc:"Cell for measuring diffusion coefficients in liquid-phase systems.",
      experiments:["Liquid-phase diffusivity","Concentration profile analysis","Temperature effects"],
      related:["CERa-MKII"] },
    { id:"CES", name:"Wetted Wall Gas Absorption Column", cat:"reactors", use:"Research",
      desc:"Wetted-wall column for measuring gas-absorption mass-transfer coefficients.",
      experiments:["Gas-film mass transfer coefficient","Liquid-film resistance","Absorption of CO₂"],
      related:["UOP7-MKII"] },
    { id:"CET-MKII", name:"Tubular Reactor", cat:"reactors", use:"Research",
      desc:"Coiled tubular reactor for studying plug-flow kinetics.",
      experiments:["PFR conversion vs residence time","Axial dispersion","Temperature profile effects"],
      related:["CEXC","CEM-MKII","CEY","CEZ"] },
    { id:"CEU", name:"Catalytic Reactors", cat:"reactors", use:"Research",
      desc:"Packed-bed catalytic reactor for studying heterogeneous catalysis.",
      experiments:["Catalyst activity","Temperature and space-time effects","Deactivation observation"],
      related:["CEXC","CET-MKII"] },
    { id:"CEY", name:"Laminar Flow Reactor", cat:"reactors", use:"Research",
      desc:"Laminar-flow tubular reactor for studying non-ideal-flow kinetics.",
      experiments:["Laminar RTD","Conversion deviation from PFR","Re dependence"],
      related:["CEXC","CEZ","CET-MKII"] },
    { id:"CEZ", name:"Plug Flow Reactor", cat:"reactors", use:"Research",
      desc:"Plug-flow tubular reactor optimised for near-ideal PFR behaviour.",
      experiments:["Near-ideal PFR conversion","Axial concentration profile","Comparison with CSTR cascade"],
      related:["CEXC","CEY","CEM-MKII"] },

    // ============== BE Series – Biochemical Engineering ==============
    { id:"BE1", name:"Batch Enzyme Reactor", cat:"biochem", use:"Research",
      desc:"Temperature-controlled stirred vessel for batch enzyme-kinetics studies.",
      experiments:["Michaelis-Menten kinetics","Km and Vmax determination","Enzyme inhibition studies"],
      related:["BE2"] },
    { id:"BE2", name:"Chromatography Unit", cat:"biochem", use:"Research",
      desc:"Laboratory chromatography column for protein / biomolecule separation studies.",
      experiments:["Elution profiles","Resolution vs flow rate","Column efficiency (plates)"],
      related:["BE1"] },
    { id:"BE3", name:"Anaerobic Column Reactor", cat:"biochem", use:"Research",
      desc:"Up-flow anaerobic column reactor for studying anaerobic digestion kinetics.",
      experiments:["Biogas yield","Organic loading rate","HRT effects"],
      related:["BE4","W8"] },
    { id:"BE4", name:"Anaerobic Tank Reactor", cat:"biochem", use:"Research",
      desc:"Stirred anaerobic tank reactor for broader anaerobic treatment studies.",
      experiments:["Volumetric biogas production","Substrate removal efficiency","Temperature effects"],
      related:["BE3","W8"] },

    // ============== CM Series – Internal Combustion Engines ==============
    // Referenced on armfield.co.uk products page but not fully listed in the
    // overview. Keeping commonly documented CM11 + CM12 entries only.
    { id:"CM11", name:"Small Engine Test Set (Gasoline)", cat:"ic-engines", use:"Research",
      desc:"Instrumented small gasoline engine test bed with eddy-current dynamometer.",
      experiments:["Brake power vs speed","Specific fuel consumption","Thermal efficiency","Heat balance"],
      related:["CM12"] },
    { id:"CM12", name:"Small Engine Test Set (Diesel)", cat:"ic-engines", use:"Research",
      desc:"Small diesel engine test bed with dynamometer and provision for emissions sampling.",
      experiments:["Diesel performance mapping","Volumetric efficiency","Load / speed characterisation"],
      related:["CM11"] },

    // ============== PCT Series – Process Control Teaching ==============
    { id:"PCT23MKII", name:"Process Plant Trainer", cat:"process-control", use:"Research",
      desc:"Multi-loop pilot-scale process rig emulating an industrial control environment.",
      experiments:["Multi-loop control","Cascade and ratio control","Loop interaction studies"],
      related:["PCT55","PCT60"] },
    { id:"PCT55", name:"Programmable Logic Controller", cat:"process-control", use:"Teaching",
      desc:"PLC trainer covering discrete logic, timers and ladder programming.",
      experiments:["Ladder-logic programming","Discrete sequence control","Fault simulation"],
      related:["PCT23MKII"] },
    { id:"PCT56", name:"Sensor Conditioning and Calibration Trainer", cat:"process-control", use:"Teaching",
      desc:"Signal-conditioning trainer covering common industrial sensors and transducers.",
      experiments:["Bridge and op-amp conditioning","4–20 mA loops","Sensor calibration"],
      related:["PCT55"] },
    { id:"PCT60", name:"Level Control", cat:"process-control", use:"Teaching",
      desc:"Single-loop level control rig with tank, sensor and control valve.",
      experiments:["PID tuning","Load disturbance response","Integral action effects"],
      related:["PCT61","PCT62","PCT63"] },
    { id:"PCT61", name:"Flow Control", cat:"process-control", use:"Teaching",
      desc:"Single-loop flow control rig with orifice meter and control valve.",
      experiments:["Flow PID tuning","Valve characterisation","Disturbance rejection"],
      related:["PCT60","PCT62","PCT63"] },
    { id:"PCT62", name:"Temperature Control", cat:"process-control", use:"Teaching",
      desc:"Heated vessel for first-order temperature loop studies.",
      experiments:["First-order response","PID tuning for thermal loops","Dead time effects"],
      related:["PCT60","PCT61","PCT63"] },
    { id:"PCT63", name:"Pressure Control", cat:"process-control", use:"Teaching",
      desc:"Pressurised-vessel pressure loop with control valve and transmitter.",
      experiments:["Pressure PID tuning","Fast vs slow loop comparison","Regulator characterisation"],
      related:["PCT60","PCT61","PCT62"] },
    { id:"PCT64", name:"Servo Pendulum", cat:"process-control", use:"Research",
      desc:"Inverted-pendulum servo control rig for advanced control teaching.",
      experiments:["Inverted pendulum stabilisation","State-feedback control","System identification"],
      related:["PCT23MKII"] },

    // ============== S Series – Applied Hydraulics & Hydrology ==============
    { id:"S1", name:"Drainage and Seepage Tank", cat:"hydraulics", use:"Teaching",
      desc:"Glass-fronted tank for demonstrating groundwater flow, flow nets and well drawdown.",
      experiments:["Flow nets under dams","Well drawdown curves","Seepage beneath sheet piles"],
      related:["S11"] },
    { id:"S2", name:"Mobile Bed and Flow Visualisation Tanks", cat:"hydraulics", use:"Teaching",
      desc:"Combined mobile-bed and flow visualisation tanks for sediment and flow observation.",
      experiments:["Mobile bed scour","Flow around structures","Sediment transport visualisation"],
      related:["S8-MKII","S28"] },
    { id:"S8-MKII", name:"Sediment Transport Demonstration Channel", cat:"hydraulics", use:"Research",
      desc:"Recirculating tilting channel for studying sediment incipient motion and bed forms.",
      experiments:["Shields parameter","Bedform evolution","Bed load transport rates"],
      related:["S28","C4-MKII"] },
    { id:"S11", name:"Ground Water Flow Unit", cat:"hydraulics", use:"Teaching",
      desc:"Groundwater apparatus demonstrating aquifer flow and pumping behaviour.",
      experiments:["Aquifer drawdown cones","Darcy's law","Observation well behaviour"],
      related:["S1"] },
    { id:"S16", name:"Hydraulic Flow Demonstrator", cat:"hydraulics", use:"Teaching",
      desc:"Multi-feature open-channel demonstrator for weirs, gates and hydraulic jumps.",
      experiments:["Hydraulic jump formation","Weir and sluice discharge","Specific energy diagrams"],
      related:["C4-MKII","S17"] },
    { id:"S17", name:"River Flow Simulator", cat:"hydraulics", use:"Research",
      desc:"Simulated river reach with sediment and structures for fluvial geomorphology studies.",
      experiments:["Meander formation","Bank erosion processes","Flood routing"],
      related:["S16","S28"] },
    { id:"S10", name:"Rainfall Hydrographs", cat:"hydraulics", use:"Teaching",
      desc:"Rainfall simulator and catchment tray for runoff hydrograph studies.",
      experiments:["Rainfall-runoff hydrographs","Catchment area effects","Infiltration rates"],
      related:["S12","FEL3"] },
    { id:"S12", name:"Advanced Environmental Hydrology System", cat:"hydraulics", use:"Research",
      desc:"Advanced catchment rig combining rainfall, infiltration and stream-flow modelling.",
      experiments:["Integrated catchment hydrology","Infiltration–runoff coupling","Unit hydrograph derivation"],
      related:["S10","FEL3"] },
    { id:"S28", name:"Sediment Erosion Flume", cat:"hydraulics", use:"Research",
      desc:"Erosion-focused flume for studying bed and bank erosion processes.",
      experiments:["Erosion threshold studies","Bank stability experiments","Sediment yield measurement"],
      related:["S8-MKII","S17"] },
    { id:"FEL2", name:"Soil/Water Model Tank", cat:"hydraulics", use:"Teaching",
      desc:"Soil-water tank for demonstrating saturated-unsaturated flow.",
      experiments:["Capillary rise","Soil moisture distribution","Darcy flow in soil"],
      related:["FEL3"] },
    { id:"FEL3", name:"Rainfall Simulator", cat:"hydraulics", use:"Teaching",
      desc:"Controlled rainfall simulator for runoff, infiltration and erosion experiments.",
      experiments:["Rainfall intensity control","Infiltration measurement","Runoff coefficient"],
      related:["S10","FEL2"] },

    // Research flumes (listed separately on Armfield site)
    { id:"S60-S80-S100", name:"Standard Teaching and Research Flumes", cat:"research-flume", use:"Research",
      desc:"Standard-range teaching and research flumes (S60, S80, S100) for open-channel studies.",
      experiments:["Open-channel hydraulics research","Sediment and hydraulic-jump studies","Fluvial modelling"],
      related:["C4-MKII","S28"] },

    // ============== H Series – Hydraulic Instruments ==============
    { id:"H1-7-H1-8", name:"Digital Hook & Point Gauges", cat:"h-instruments", use:"Teaching",
      desc:"Precision digital hook/point gauges for accurate water-surface measurement.",
      experiments:["Water surface profiling","Weir-crest reference","High-accuracy level measurement"],
      related:["H12"] },
    { id:"H12", name:"Liquid Manometers & Meters", cat:"h-instruments", use:"Teaching",
      desc:"Range of U-tube, inclined and multi-limb liquid manometers for pressure measurement.",
      experiments:["Differential pressure measurement","Inclined manometer sensitivity","Multi-point pressure readings"],
      related:["H14/2"] },
    { id:"H14/2", name:"Computer Compatible Manometer Bank", cat:"h-instruments", use:"Research",
      desc:"Electronic manometer bank with PC interface for multi-tapping pressure logging.",
      experiments:["Multi-point pressure logging","Computer-based pressure visualisation"],
      related:["H12"] },
    { id:"H30", name:"Pitot Tubes", cat:"h-instruments", use:"Teaching",
      desc:"Standard Pitot-static tubes for velocity measurement in ducts and channels.",
      experiments:["Velocity profiling","Stagnation pressure measurement","Flow-meter calibration"],
      related:["F1-33"] },
    { id:"H33", name:"Propeller Velocity Flowmeter", cat:"h-instruments", use:"Research",
      desc:"Propeller-type velocity flow meter for open-channel / flume measurements.",
      experiments:["Point velocity measurement","Open-channel flow profiling"],
      related:["H30"] },
    { id:"H40-MKII", name:"Wave Probe System", cat:"h-instruments", use:"Research",
      desc:"Capacitive wave probe system for measuring surface-wave elevation.",
      experiments:["Wave height and period","Wave spectrum measurement","Resonance studies"],
      related:[] },
    { id:"H41", name:"Laser PIV System", cat:"h-instruments", use:"Research",
      desc:"Laser-based Particle Image Velocimetry system for 2-D flow-field measurement.",
      experiments:["Whole-field velocity measurement","Vorticity fields","Flow around models"],
      related:["C16"] },

    // ============== FE Series – Irrigation Water Management ==============
    { id:"FEL4", name:"Soil Moisture Suction Sand Table", cat:"irrigation", use:"Research",
      desc:"Soil-moisture suction table for characterising soil water-retention curves.",
      experiments:["Water retention curve","Soil suction measurement","Field capacity determination"],
      related:["FEL5-MKII","FEL6"] },
    { id:"FEL5-MKII", name:"Demonstration Infiltration Apparatus", cat:"irrigation", use:"Teaching",
      desc:"Vertical column apparatus for demonstrating infiltration into different soil profiles.",
      experiments:["Infiltration rates vs soil type","Effect of antecedent moisture","Ponded infiltration"],
      related:["FEL4"] },
    { id:"FEL6", name:"Demonstration Lysimeter", cat:"irrigation", use:"Research",
      desc:"Laboratory lysimeter for measuring percolation and evapotranspiration.",
      experiments:["Drainage quantification","Evapotranspiration balance","Irrigation efficiency"],
      related:["FEL4"] },
    { id:"FEL10", name:"Drain Permeameter", cat:"irrigation", use:"Teaching",
      desc:"Constant- and falling-head permeameter for measuring soil hydraulic conductivity.",
      experiments:["Constant-head permeability","Falling-head permeability","Darcy coefficient"],
      related:["FEL4"] },
    { id:"FEX26-1/2/3", name:"Parshall Flumes", cat:"irrigation", use:"Teaching",
      desc:"Set of Parshall flumes for discharge measurement in open channels.",
      experiments:["Parshall flume calibration","Discharge–head relationships","Free vs submerged flow"],
      related:["FEX26-4/5/6"] },
    { id:"FEX26-4/5/6", name:"Washington State College (WSC) Flumes", cat:"irrigation", use:"Teaching",
      desc:"Range of WSC flumes for small-stream open-channel discharge measurement.",
      experiments:["WSC flume calibration","Small-channel discharge measurement"],
      related:["FEX26-1/2/3"] },
    { id:"FEX26-7", name:"Thin Plate Weirs & Accessories", cat:"irrigation", use:"Teaching",
      desc:"Thin-plate weir set for standard discharge measurement in open channels.",
      experiments:["V-notch and rectangular weir calibration","Standard weir equations"],
      related:["F1-13-MKII"] },

    // ============== W Series – Water Treatment ==============
    { id:"W1", name:"Flocculation Test Units", cat:"water-treat", use:"Teaching",
      desc:"Multi-stirrer jar-test rig for coagulation / flocculation optimisation.",
      experiments:["Jar test coagulant dosing","Floc formation and settling","Optimum coagulant dose"],
      related:["W2-MKII","W4-MKII"] },
    { id:"W2-MKII", name:"Sedimentation Studies Apparatus", cat:"water-treat", use:"Teaching",
      desc:"Batch settling columns for particle settling velocity studies.",
      experiments:["Stokes' law verification","Type I discrete settling","Hindered settling"],
      related:["W7-MKII","W1"] },
    { id:"W3-MKII", name:"Permeability - Fluidisation Studies Apparatus", cat:"water-treat", use:"Teaching",
      desc:"Packed / fluidised bed column for permeability and fluidisation experiments.",
      experiments:["Darcy permeability","Minimum fluidisation velocity","Bed expansion"],
      related:["CEL-MKII"] },
    { id:"W4-MKII", name:"Filterability Apparatus", cat:"water-treat", use:"Research",
      desc:"Laboratory filterability rig for characterising cake- and membrane-filter performance.",
      experiments:["Specific resistance to filtration","Compressibility of cake","Throughput analysis"],
      related:["W5-MKII","UOP12"] },
    { id:"W5-MKII", name:"Deep Bed Filter Column", cat:"water-treat", use:"Teaching",
      desc:"Transparent sand filter column with piezometer tappings along the bed depth.",
      experiments:["Headloss vs run time","Backwash effectiveness","Filter ripening"],
      related:["W1","W4-MKII"] },
    { id:"W7-MKII", name:"Model Sedimentation Tank", cat:"water-treat", use:"Teaching",
      desc:"Continuous-flow sedimentation tank for studying real-scale settling behaviour.",
      experiments:["Surface overflow rate","Tracer residence time","Removal efficiency"],
      related:["W2-MKII","W1"] },
    { id:"W8", name:"Anaerobic Digester", cat:"water-treat", use:"Research",
      desc:"Laboratory anaerobic digester for studying biogas production and sludge stabilisation.",
      experiments:["Biogas yield","Volatile solids reduction","HRT effects"],
      related:["W11","BE3","BE4"] },
    { id:"W9-MKII", name:"Ion Exchange Unit", cat:"water-treat", use:"Research",
      desc:"Ion-exchange column for softening, demineralisation and exchange-kinetics studies.",
      experiments:["Breakthrough curves","Exchange capacity","Regeneration efficiency"],
      related:["UOP15"] },
    { id:"W10-MKII", name:"Aeration Unit", cat:"water-treat", use:"Research",
      desc:"Aeration tank for studying oxygen transfer and KLa determination.",
      experiments:["Oxygen transfer coefficient KLa","Effect of aerator type","DO dynamics"],
      related:["W11"] },
    { id:"W11", name:"Aerobic Digester", cat:"water-treat", use:"Research",
      desc:"Aerobic digester for sludge stabilisation and volatile-solids reduction studies.",
      experiments:["VS reduction vs SRT","Oxygen uptake rate","Digester temperature effects"],
      related:["W8","W10-MKII"] },

    // ============== FT Series – Educational Food Technology ==============
    // (Published as "FT Series - Educational Food Technology" on armfield.co.uk;
    // specific sub-models on that page were category-grouped rather than itemised —
    // flagship educational units shown here.)
    { id:"FT-Series", name:"FT Series – Educational Food Technology", cat:"ft-edu", use:"Teaching",
      desc:"Educational range introducing students to food-processing operations (pasteurisation, mixing, drying, separation).",
      experiments:["Introductory food-processing demonstrations","Safe educational-scale operation","Curriculum-aligned experiments"],
      related:["FT43","FT174","FT102LT"] },

    // ============== IFT Series – Industrial Food Technology ==============
    { id:"FT2", name:"Hammer-Beater Mill", cat:"ift", use:"Research",
      desc:"Laboratory hammer / beater mill for size reduction of friable food materials.",
      experiments:["Particle size reduction","Size distribution analysis","Energy consumption"],
      related:["FT5"] },
    { id:"FT5", name:"Ribbon and Cone Blender", cat:"ift", use:"Research",
      desc:"Dry-powder blender combining ribbon and cone mixing geometries.",
      experiments:["Blend uniformity","Mixing time determination","Segregation studies"],
      related:["FT2"] },
    { id:"FT14", name:"Plate and Frame Filter Press", cat:"ift", use:"Research",
      desc:"Laboratory plate-and-frame filter press for solids-liquid separation.",
      experiments:["Cake filtration kinetics","Filter-cloth selection","Cake washing"],
      related:["FT15","UOP12"] },
    { id:"FT15", name:"Disc Bowl Centrifuge", cat:"ift", use:"Research",
      desc:"Laboratory disc-stack centrifuge for separating immiscible liquids or fine solids.",
      experiments:["Cream-skim separation","Feed rate effects","Sigma-value scaling"],
      related:["FT14","FT27"] },
    { id:"FT17", name:"Cross Flow Membrane Filtration", cat:"ift", use:"Research",
      desc:"Cross-flow membrane rig supporting MF / UF / NF / RO modules.",
      experiments:["Flux vs TMP","Concentration polarisation","Solute rejection"],
      related:["FT18"] },
    { id:"FT18", name:"Modular Cross Flow Filtration", cat:"ift", use:"Research",
      desc:"Pilot-scale modular cross-flow filtration system accepting multiple membrane module types.",
      experiments:["Module comparison studies","Flux decline profiles","Cleaning cycle optimisation"],
      related:["FT17"] },
    { id:"FT19", name:"Autoclave", cat:"ift", use:"Research",
      desc:"Laboratory autoclave for thermal-sterilisation studies.",
      experiments:["F₀ determination","Heat penetration curves","Sterilisation validation"],
      related:["FT43","FT174"] },
    { id:"FT20", name:"Cheese Vat", cat:"ift", use:"Research",
      desc:"Jacketed cheese vat with cutting / stirring for laboratory cheese trials.",
      experiments:["Curd formation and cutting","Heat treatment profile","Whey separation"],
      related:["FT21"] },
    { id:"FT21", name:"Butter Churn and Butter Making Accessories", cat:"ift", use:"Research",
      desc:"Small-batch butter churn for laboratory butter-making.",
      experiments:["Churning time vs temperature","Butter yield","Moisture in butter"],
      related:["FT20"] },
    { id:"FT22", name:"Rising Film Evaporator", cat:"ift", use:"Research",
      desc:"Small rising-film evaporator processing samples from around 2 litres.",
      experiments:["Overall heat transfer U","Boiling point elevation","Evaporation capacity"],
      related:["UOP20X"] },
    { id:"FT25X", name:"Modular Scraped Surface Heat Exchanger Systems", cat:"ift", use:"Research",
      desc:"Modular scraped-surface heat exchanger for viscous / fouling-prone food products.",
      experiments:["Heating of viscous fluids","Fouling rate measurement","Residence time distribution"],
      related:["FT174"] },
    { id:"FT27", name:"CentriPeel Centrifuge", cat:"ift", use:"Research",
      desc:"CentriPeel laboratory centrifuge for solids dewatering and peel-style operation.",
      experiments:["Dewatering efficiency","Solids handling studies","Cake dryness characterisation"],
      related:["FT15"] },
    { id:"FT28", name:"Oil Extraction Screw Press", cat:"ift", use:"Research",
      desc:"Continuous screw press for mechanical expression of oilseeds.",
      experiments:["Oil yield vs pressure","Residual oil in meal","Seed pretreatment effects"],
      related:["FT29"] },
    { id:"FT29", name:"Batch Solvent Extraction and Desolventising Unit", cat:"ift", use:"Research",
      desc:"Batch solvent extractor and desolventiser for oilseed and natural-product extraction.",
      experiments:["Solvent extraction efficiency","Desolventising kinetics","Solvent recovery"],
      related:["FT28"] },
    { id:"FT30-MKIII", name:"Spray Dryer", cat:"ift", use:"Research",
      desc:"Co-current laboratory spray dryer for producing powders from aqueous feeds.",
      experiments:["Drying kinetics","Outlet-temperature effects on moisture","Yield vs feed rate"],
      related:["FT31","FT32","FT80"] },
    { id:"FT31", name:"Laboratory Fluid Bed Dryer", cat:"ift", use:"Research",
      desc:"Small fluid-bed dryer for studying fluidised drying of particulates.",
      experiments:["Drying curves","Minimum fluidisation velocity","Bed temperature profile"],
      related:["FT30-MKIII"] },
    { id:"FT32", name:"Drum Dryer", cat:"ift", use:"Research",
      desc:"Laboratory drum dryer for thin-film drying of pastes and slurries.",
      experiments:["Drum drying throughput","Film thickness effects","Product moisture characterisation"],
      related:["FT30-MKIII"] },
    { id:"FT33MkII", name:"Vacuum Freeze Dryer", cat:"ift", use:"Research",
      desc:"Laboratory vacuum freeze dryer for heat-sensitive products.",
      experiments:["Primary and secondary drying","Sublimation rate","Product rehydration quality"],
      related:["FT34MKII","FT36"] },
    { id:"FT34MKII", name:"Contact Plate Freezer", cat:"ift", use:"Research",
      desc:"Contact plate freezer for rapid laboratory freezing trials.",
      experiments:["Freezing curve characterisation","Heat flux measurement","Thickness effects"],
      related:["FT36","FT33MkII"] },
    { id:"FT36", name:"Blast Freezer", cat:"ift", use:"Research",
      desc:"Laboratory blast freezer for air-blast freezing trials.",
      experiments:["Air velocity effects","Freezing time calculation","Weight loss quantification"],
      related:["FT34MKII"] },
    { id:"FT43", name:"Laboratory Pasteuriser", cat:"ift", use:"Research",
      desc:"Compact laboratory HTST pasteuriser with plate exchangers and holding tube.",
      experiments:["HTST pasteurisation regimes","Regeneration efficiency","Lethality F₀"],
      related:["FT75","FT174"] },
    { id:"FT51", name:"Continuous In-line Deaerator", cat:"ift", use:"Research",
      desc:"Inline deaerator for removing dissolved gases from liquid food products.",
      experiments:["Dissolved oxygen removal","Vacuum level effects","Product quality impact"],
      related:["FT174"] },
    { id:"FT52", name:"CIP Unit", cat:"ift", use:"Research",
      desc:"Clean-in-place unit for validating CIP cycles on pilot food equipment.",
      experiments:["CIP cycle validation","Chemical and thermal CIP","Rinse-water monitoring"],
      related:["FT174","FT43"] },
    { id:"FT63", name:"Laboratory Process Chiller", cat:"ift", use:"Research",
      desc:"Laboratory recirculating chiller for supplying cold utility to pilot rigs.",
      experiments:["Cooling-load matching","Setpoint stability","Integration with pilot units"],
      related:["FT64"] },
    { id:"FT64", name:"Laboratory Process Chiller", cat:"ift", use:"Research",
      desc:"Alternate-capacity laboratory process chiller for pilot-rig cooling utility.",
      experiments:["Cooling capacity characterisation","Integration trials","Setpoint response"],
      related:["FT63"] },
    { id:"FT66", name:"Neutraliser/Washer/Bleacher", cat:"ift", use:"Research",
      desc:"Combined neutraliser, washer and bleacher for edible-oil refining studies.",
      experiments:["Free fatty acid neutralisation","Wash-water separation","Bleaching efficiency"],
      related:["FT67","FT68"] },
    { id:"FT67", name:"Hydrogenation Unit", cat:"ift", use:"Research",
      desc:"Laboratory oil hydrogenation unit for studying catalytic hardening of edible oils.",
      experiments:["Iodine value reduction","Catalyst effects","Selectivity characterisation"],
      related:["FT66","FT68"] },
    { id:"FT68", name:"Deodorising Unit", cat:"ift", use:"Research",
      desc:"Vacuum steam deodoriser for the final stage of edible oil refining.",
      experiments:["Volatile removal efficiency","Flavour / odour improvement","Vacuum level effects"],
      related:["FT66","FT67"] },
    { id:"FT74XA", name:"HTST/UHT System", cat:"ift", use:"Research",
      desc:"HTST / UHT processing system covering heat treatment of liquid foods.",
      experiments:["HTST vs UHT comparison","Regeneration efficiency","Product-quality trials"],
      related:["FT174","FT94X"] },
    { id:"FT75", name:"Laboratory Pasteuriser", cat:"ift", use:"Research",
      desc:"Alternative laboratory pasteuriser layout for smaller-batch HTST trials.",
      experiments:["Batch HTST trials","Thermal lethality","Product quality monitoring"],
      related:["FT43","FT174"] },
    { id:"FT80", name:"Tall Form Spray Dryer", cat:"ift", use:"Research",
      desc:"Tall-form laboratory spray dryer for products requiring longer drying residence time.",
      experiments:["Extended residence drying","Powder morphology","Yield optimisation"],
      related:["FT30-MKIII"] },
    { id:"FT83XA", name:"Sterile Filling System", cat:"ift", use:"Research",
      desc:"Sterile / aseptic filling system for liquid-food pilot trials.",
      experiments:["Aseptic filling trials","Sterility validation","Integration with UHT"],
      related:["FT174","FT85"] },
    { id:"FT84-12", name:"Microwave UHT Add-on", cat:"ift", use:"Research",
      desc:"Microwave UHT add-on module supplementing conventional HTST / UHT systems.",
      experiments:["Microwave UHT vs conventional","Temperature uniformity","Product quality comparison"],
      related:["FT174","FT74XA"] },
    { id:"FT85", name:"Sterile Vessel", cat:"ift", use:"Research",
      desc:"Sterile holding vessel for aseptic processing pilot studies.",
      experiments:["Aseptic holding","Post-UHT integration","Sterile sampling"],
      related:["FT83XA","FT174"] },
    { id:"FT90", name:"Homogenisation Sub-Systems", cat:"ift", use:"Research",
      desc:"High-pressure homogenisation sub-system for integration into larger pilot lines.",
      experiments:["Droplet size vs pressure","Two-stage homogenisation","Emulsion stability"],
      related:["FT91","FT141"] },
    { id:"FT91", name:"Homogenisation Sub-System", cat:"ift", use:"Research",
      desc:"Alternate-spec homogenisation sub-system for smaller pilot lines.",
      experiments:["High-pressure emulsification","Particle size analysis"],
      related:["FT90"] },
    { id:"FT94LT", name:"HTST/UHT Mini Pilot System", cat:"ift", use:"Research",
      desc:"Compact mini-pilot HTST / UHT system for very small-scale trials.",
      experiments:["Mini-pilot HTST","Product development trials","Regeneration efficiency"],
      related:["FT94X","FT174"] },
    { id:"FT94X", name:"HTST/UHT Mini Pilot System", cat:"ift", use:"Research",
      desc:"Mini-pilot HTST / UHT system with extended process monitoring capability.",
      experiments:["Mini-pilot process trials","Advanced process monitoring","Regeneration / cooling sections"],
      related:["FT94LT","FT174"] },
    { id:"FT102LT", name:"Carbonator Filler", cat:"ift", use:"Research",
      desc:"Laboratory carbonator and filler unit for carbonated-beverage pilot trials.",
      experiments:["CO₂ saturation trials","Fill-level consistency","Pressure / temperature control"],
      related:["FT102X-FT104X"] },
    { id:"FT102X-FT104X", name:"Carbonator/Filler/Capper", cat:"ift", use:"Research",
      desc:"Integrated carbonator / filler / capper line for carbonated-beverage pilot studies.",
      experiments:["Continuous carbonation-filling","Capping performance","Integrated line trials"],
      related:["FT102LT"] },
    { id:"FT110DP", name:"Rapid Extractor", cat:"ift", use:"Research",
      desc:"Rapid extractor for high-throughput laboratory-scale extraction studies.",
      experiments:["Rapid solvent extraction","Yield comparison","Scale-up studies"],
      related:["FT111X"] },
    { id:"FT111X", name:"Laboratory-Scale Rapid Extractor", cat:"ift", use:"Research",
      desc:"Smaller laboratory-scale rapid extractor for formulation development.",
      experiments:["Small-sample extraction","Yield optimisation","Formulation screening"],
      related:["FT110DP"] },
    { id:"FT140X", name:"Mixing Vessels", cat:"ift", use:"Research",
      desc:"Jacketed mixing vessels for multipurpose liquid-food formulation trials.",
      experiments:["Batch formulation","Jacketed heating / cooling","Mixing-speed effects"],
      related:["FT141"] },
    { id:"FT141", name:"Multifunction Laboratory Mixer", cat:"ift", use:"Research",
      desc:"Multifunction laboratory mixer supporting a range of impellers and operations.",
      experiments:["Mixing-regime characterisation","Shear-rate studies","Multi-operation trials"],
      related:["FT140X","FT90"] },
    { id:"FT174", name:"HTST/UHT Process System", cat:"ift", use:"Research",
      desc:"Flagship Armfield modular HTST / UHT processing system for liquid-food R&D.",
      experiments:["HTST vs UHT comparison","Thermal lethality F₀","Regeneration efficiency","Product development trials"],
      related:["FT74XA","FT94X","FT83XA"] },

    // ============== CA Series – Control & Acquisition ==============
    { id:"CA-armSOFT", name:"armSOFT Control & Acquisition", cat:"daq", use:"Research",
      desc:"Data-acquisition and control software suite used across Armfield computer-controlled equipment.",
      experiments:["Multi-channel data logging","PID loop implementation","Export to CSV / MATLAB"],
      related:["HT10XC","CEXC","PCT23MKII"] },
  ],
};
